TestEvaluationRobustnessLoop
{
    theory
    {
        func Sum(from,to:Nat, arr: Nat[from~to]) -> Nat
        {
            i, result: Nat
            result:=Zero()

            loop i [from~to]
            (
                result:=Add(result,arr[i])
            )
            return result
        }
    }
}
##############################
should not throw any not handled error

